global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "weather-service"
    static_configs:
      - targets: ["weather-service:8000"]
  - job_name: "notifications-service"
    static_configs:
      - targets: ["notifications-service:8100"]
