global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "weather-service-dev"
    static_configs:
      - targets: ["weather-service-dev:8001"]
  - job_name: "notifications-service-dev"
    static_configs:
      - targets: ["notifications-service-dev:8101"]
